// Code generated by SQLBoiler 3.6.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Bookmark string
	Ogp      string
	Stat     string
	User     string
}{
	Bookmark: "bookmark",
	Ogp:      "ogp",
	Stat:     "stat",
	User:     "user",
}
